ShoppingUI/Controllers/BasketController.cs
using Application.Services.BasketServices.BasketFacade;
using Application.Services.BasketServices.GetOrCreateBasketForUser;
using Microsoft.AspNetCore.Mvc;
using ShoppingUI.Utilities;

namespace ShoppingUI.Controllers
{
    public class BasketController : Controller
    {
        private readonly IBasketService basketService;
        private readonly IConfiguration configuration;
        private string userId = null;

        public BasketController(IBasketService basketService,
            IConfiguration configuration)
        {
            this.basketService = basketService;
            this.configuration = configuration;
        }



        public async Task<IActionResult> Index()
        {
            var data = await GetOrSetBasket();
            return View(data);
        }



        [HttpPost]
        public async Task<IActionResult> Index(int productId, int quantity = 1)
        {
            var basket = await GetOrSetBasket();
            var result = await basketService.AddItem.ExecutAsync(basket.Id, productId, quantity);
            if(result == true)
            {
                return RedirectToAction(nameof(Index));

            }
            return BadRequest();
        }

        [HttpPost]
        public async Task<IActionResult> RemoveItems(int productId)
        {
            var result = await basketService.RemvoeItem.ExecuteAsync(productId);

            if(result == true)
            {
                return RedirectToAction(nameof(Index));
            }

            return BadRequest();
        }

        [HttpPost]
        public async Task<IActionResult> AddQuantites(int productId)
        {
            var result = await basketService.SetQuantity.ExecuteAsync(productId);

            if (result == true)
            {
                return RedirectToAction(nameof(Index));
            }

            return BadRequest();
        }



        private async Task<BasketDto> GetOrSetBasket()
        {
            if (User.Identity.IsAuthenticated)
            {
                userId = ClaimUtility.GetUserId(User);
                return await basketService.GetOrCreateBasket.ExecutAsync(userId);
            }
            else
            {
                setCookies();
                return await basketService.GetOrCreateBasket.ExecutAsync(userId);
            }
        }

        private void setCookies()
        {
            var basketId = configuration["BuyerCookieName"];
            if (Request.Cookies.ContainsKey(basketId))
            {
                userId = Request.Cookies[basketId];
                
            }
            if (userId is not null) return;

            userId = Guid.NewGuid().ToString();
            var cookieOptions = new CookieOptions { IsEssential = true };
            cookieOptions.Expires = DateTime.Today.AddYears(2);
            Response.Cookies.Append(basketId, userId, cookieOptions);
        }


    }
}

ShoppingUI/Controllers/ProductController.cs
using Application.Services.CommentServices.AddNewComment;
using Application.Services.CommentServices.CommentFacade;
using Application.Services.ProductServices.PLPProduct;
using Application.Services.ProductServices.ProductFacade;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ShoppingUI.Utilities;

namespace ShoppingUI.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService productService;
        private readonly ICommentService commentService;

        public ProductController(IProductService productService, ICommentService commentService)
        {
            this.productService = productService;
            this.commentService = commentService;
        }


        public async Task<IActionResult> Index(RequestPLPDto request)
        {
            var products = await productService.PLPProducts.ExecuteAsync(request);
            return View(products);
        }

        public async Task<IActionResult> Details(string? Slug)
        {
            string? userId = null;
            if (User.Identity.IsAuthenticated)
            {
                userId = ClaimUtility.GetUserId(User);
            }

            var product = await productService.PDPProducts.ExecuteAsync(Slug,userId);

            return View(product);
        }


        [Authorize]
        [Route("~/favo")]
        [HttpPost]
        public async Task<IActionResult> FavoriteOperation(bool isFavorite,int productId, string slug)
        {
            var userId = ClaimUtility.GetUserId(User);
            
            if(isFavorite == true)
            {
                await productService.FavoriteProducts.AddToFavoriteAsync(userId, productId);
                return RedirectToAction(nameof(Details), new {Slug=slug});
            }
            else
            {
                await productService.FavoriteProducts.RemoveFromFavoriteAsync(userId, productId);
                return RedirectToAction(nameof(Details), new { Slug = slug });
            }
        }


        [Authorize]
        [Route("~/addcomment")]
        [HttpPost]
        public async Task<IActionResult> AddComment(AddNewCommentDto comment, string slug)
        {
            var userid = ClaimUtility.GetUserId(User);
            await commentService.AddComment.ExecuteAsync(comment, userid);

            return RedirectToAction(nameof(Details), new { Slug = slug });
        }

        
    }
}

ShoppingUI/Areas/Customers/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShoppingWebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ShoppingWebUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ShoppingWebUI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Basket" asp-action="Index">My Basket</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-route-email="@User.Identity.Name" asp-action="Profile">
                                    @User.Identity.Name
                                </a>
                            </li>

                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }

@*                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Basket" asp-action="Index">My Basket</a>
                        </li>*@



                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ShoppingWebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>