ShoppingUI/Controllers/BasketController.cs
using Application.Services.BasketServices.BasketFacade;
using Application.Services.BasketServices.GetOrCreateBasketForUser;
using Microsoft.AspNetCore.Mvc;
using ShoppingUI.Utilities;

namespace ShoppingUI.Controllers
{
    public class BasketController : Controller
    {
        private readonly IBasketService basketService;
        private readonly IConfiguration configuration;
        private string userId = null;

        public BasketController(IBasketService basketService,
            IConfiguration configuration)
        {
            this.basketService = basketService;
            this.configuration = configuration;
        }



        public async Task<IActionResult> Index()
        {
            var data = await GetOrSetBasket();
            return View(data);
        }



        [HttpPost]
        public async Task<IActionResult> Index(int productId, int quantity = 1)
        {
            var basket = await GetOrSetBasket();
            var result = await basketService.AddItem.ExecutAsync(basket.Id, productId, quantity);
            if(result == true)
            {
                return RedirectToAction(nameof(Index));

            }
            return BadRequest();
        }

        [HttpPost]
        public async Task<IActionResult> RemoveItems(int productId)
        {
            var result = await basketService.RemvoeItem.ExecuteAsync(productId);

            if(result == true)
            {
                return RedirectToAction(nameof(Index));
            }

            return BadRequest();
        }

        [HttpPost]
        public async Task<IActionResult> AddQuantites(int productId)
        {
            var result = await basketService.SetQuantity.ExecuteAsync(productId);

            if (result == true)
            {
                return RedirectToAction(nameof(Index));
            }

            return BadRequest();
        }



        private async Task<BasketDto> GetOrSetBasket()
        {
            if (User.Identity.IsAuthenticated)
            {
                userId = ClaimUtility.GetUserId(User);
                return await basketService.GetOrCreateBasket.ExecutAsync(userId);
            }
            else
            {
                setCookies();
                return await basketService.GetOrCreateBasket.ExecutAsync(userId);
            }
        }

        private void setCookies()
        {
            var basketId = configuration["BuyerCookieName"];
            if (Request.Cookies.ContainsKey(basketId))
            {
                userId = Request.Cookies[basketId];
                
            }
            if (userId is not null) return;

            userId = Guid.NewGuid().ToString();
            var cookieOptions = new CookieOptions { IsEssential = true };
            cookieOptions.Expires = DateTime.Today.AddYears(2);
            Response.Cookies.Append(basketId, userId, cookieOptions);
        }


    }
}

ShoppingUI/Controllers/OrderController.cs
using Application.Services.BasketServices.BasketFacade;
using Application.Services.CustomerServices.CustomerFacade;
using Application.Services.OrderServices.OrderFacade;
using Domain.Entites.Orders;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ShoppingUI.Models.ViewModels;
using ShoppingUI.Utilities;

namespace ShoppingUI.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IBasketService basketService;
        private readonly ICustomerService customerService;
        private readonly IOrderService orderService;

        public OrderController(IBasketService basketService,
            ICustomerService customerService,
            IOrderService orderService)
        {
            this.basketService = basketService;
            this.customerService = customerService;
            this.orderService = orderService;
        }

        public async Task<IActionResult> ShippingPayment()
        {
            var userId = ClaimUtility.GetUserId(User);
            var model = new OrderViewModels();
            model.Basket = await basketService.GetBasket.ExecutAsync(userId);
            model.Addresses = await customerService.GetAddress.ExecuteAsync(userId);
            return View(model);
        }



        [HttpPost]
        public async Task<IActionResult> ShippingPayment(int addressId, PaymentMethode paymentMethode)
        {
            var userId = ClaimUtility.GetUserId(User);

            var orderid = await orderService.CreateOrder.ExecuteAsync(userId, addressId, paymentMethode);

            return RedirectToAction(nameof(ShippingPayment));
        }
    }
}

ShoppingUI/Views/Basket/Index.cshtml
@using Application.Services.BasketServices.GetOrCreateBasketForUser
@model BasketDto

<div class="container">
    <header>
        <h1>Basket Page</h1>
        <br />
        <hr />
        <br />

    </header>
    @if(Model is not null)
    {
        <div class="row">
            <div class="col-sm-4">
                <h4>Number of Products : @Model.BasketItems.Count</h4>
            </div>

            <div class="col-sm-4">
                <h4>Total Price : @Model.TotalPrice.ToString("n0")</h4>
            </div>
        </div>
    }
    
    
    <br /><hr /><br />
    <div class="row">
        @if(Model is null || Model.BasketItems.Count == 0 )
        {
            <h3>Not any item added!!</h3>
        }
        else
        {
            @foreach (var item in Model.BasketItems)
            {
                <div class="col-12">
                    <div class="card" style="width: 18rem;">
                      <img src="@item.ImageUrl" class="card-img-top" alt="...">
                      <div class="card-body">
                        <h5 class="card-title">@item.Price</h5>
                        <form asp-action="RemoveItems" asp-controller="Basket" method="post">
                            <input type="hidden" name="productId" value="@item.ProductId">
                            <input type="submit" value="Remove" class="btn btn-danger">
                        </form>


                        <form asp-action="AddQuantites" asp-controller="Basket" method="post">
                            <input type="hidden" name="productId" value="@item.ProductId"> 
                            <button  class="btn btn-success" onclick="submit()">+</button>
                        </form>

                        
                      </div>
                    </div>
                </div>
            }
        }

        


    </div>


    <a asp-action="ShippingPayment" asp-controller="Order" class="btn btn-warning">Go To Shipping</a>

</div>